[2025-02-19T10:24:47.177+0000] {taskinstance.py:1402} DEBUG - previous_execution_date was called
[2025-02-19T10:24:47.199+0000] {__init__.py:54} DEBUG - Loading core task runner: StandardTaskRunner
[2025-02-19T10:24:47.214+0000] {taskinstance.py:1402} DEBUG - previous_execution_date was called
[2025-02-19T10:24:47.219+0000] {base_task_runner.py:73} DEBUG - Planning to run as the  user
[2025-02-19T10:24:47.223+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-19T10:24:47.232+0000] {taskinstance.py:2624} DEBUG - <TaskInstance: etl_pipeline.ingest_postgres manual__2025-02-19T10:24:41.603923+00:00 [queued]> dependency 'Task Instance State' PASSED: True, Task state queued was valid.
[2025-02-19T10:24:47.233+0000] {taskinstance.py:2624} DEBUG - <TaskInstance: etl_pipeline.ingest_postgres manual__2025-02-19T10:24:41.603923+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2025-02-19T10:24:47.238+0000] {taskinstance.py:2624} DEBUG - <TaskInstance: etl_pipeline.ingest_postgres manual__2025-02-19T10:24:41.603923+00:00 [queued]> dependency 'Trigger Rule' PASSED: True, The task instance did not have any upstream tasks.
[2025-02-19T10:24:47.239+0000] {taskinstance.py:2624} DEBUG - <TaskInstance: etl_pipeline.ingest_postgres manual__2025-02-19T10:24:41.603923+00:00 [queued]> dependency 'Task Instance Not Running' PASSED: True, Task is not in running state.
[2025-02-19T10:24:47.239+0000] {taskinstance.py:2624} DEBUG - <TaskInstance: etl_pipeline.ingest_postgres manual__2025-02-19T10:24:41.603923+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2025-02-19T10:24:47.239+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline.ingest_postgres manual__2025-02-19T10:24:41.603923+00:00 [queued]>
[2025-02-19T10:24:47.239+0000] {taskinstance.py:2624} DEBUG - <TaskInstance: etl_pipeline.ingest_postgres manual__2025-02-19T10:24:41.603923+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2025-02-19T10:24:47.239+0000] {taskinstance.py:2624} DEBUG - <TaskInstance: etl_pipeline.ingest_postgres manual__2025-02-19T10:24:41.603923+00:00 [queued]> dependency 'Task Concurrency' PASSED: True, Task concurrency is not set.
[2025-02-19T10:24:47.241+0000] {taskinstance.py:2624} DEBUG - <TaskInstance: etl_pipeline.ingest_postgres manual__2025-02-19T10:24:41.603923+00:00 [queued]> dependency 'Trigger Rule' PASSED: True, The task instance did not have any upstream tasks.
[2025-02-19T10:24:47.246+0000] {taskinstance.py:2624} DEBUG - <TaskInstance: etl_pipeline.ingest_postgres manual__2025-02-19T10:24:41.603923+00:00 [queued]> dependency 'Pool Slots Available' PASSED: True, There are enough open slots in default_pool to execute the task
[2025-02-19T10:24:47.248+0000] {taskinstance.py:2624} DEBUG - <TaskInstance: etl_pipeline.ingest_postgres manual__2025-02-19T10:24:41.603923+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2025-02-19T10:24:47.249+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline.ingest_postgres manual__2025-02-19T10:24:41.603923+00:00 [queued]>
[2025-02-19T10:24:47.249+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 3
[2025-02-19T10:24:47.261+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): ingest_postgres> on 2025-02-19 10:24:41.603923+00:00
[2025-02-19T10:24:47.269+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=79) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-19T10:24:47.271+0000] {standard_task_runner.py:72} INFO - Started process 85 to run task
[2025-02-19T10:24:47.271+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_pipeline', 'ingest_postgres', 'manual__2025-02-19T10:24:41.603923+00:00', '--job-id', '75', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmp_anr3075']
[2025-02-19T10:24:47.272+0000] {standard_task_runner.py:105} INFO - Job 75: Subtask ingest_postgres
[2025-02-19T10:24:47.273+0000] {cli_action_loggers.py:79} DEBUG - Calling callbacks: [<function default_action_log at 0x7fce9a04a340>]
[2025-02-19T10:24:47.323+0000] {taskinstance.py:1402} DEBUG - previous_execution_date was called
[2025-02-19T10:24:47.335+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_pipeline.ingest_postgres manual__2025-02-19T10:24:41.603923+00:00 [running]> on host d01efb841c31
[2025-02-19T10:24:47.336+0000] {settings.py:612} DEBUG - Disposing DB connection pool (PID 85)
[2025-02-19T10:24:47.336+0000] {settings.py:475} DEBUG - Setting up DB connection pool (PID 85)
[2025-02-19T10:24:47.337+0000] {settings.py:547} DEBUG - settings.prepare_engine_args(): Using NullPool
[2025-02-19T10:24:47.395+0000] {taskinstance.py:1402} DEBUG - previous_execution_date was called
[2025-02-19T10:24:47.404+0000] {taskinstance.py:2383} DEBUG - Clearing XCom data
[2025-02-19T10:24:47.417+0000] {retries.py:95} DEBUG - Running RenderedTaskInstanceFields.write with retries. Try 1 of 3
[2025-02-19T10:24:47.433+0000] {retries.py:95} DEBUG - Running RenderedTaskInstanceFields._do_delete_old_records with retries. Try 1 of 3
[2025-02-19T10:24:47.447+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='your_email@example.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_pipeline' AIRFLOW_CTX_TASK_ID='ingest_postgres' AIRFLOW_CTX_EXECUTION_DATE='2025-02-19T10:24:41.603923+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-19T10:24:41.603923+00:00'
[2025-02-19T10:24:47.448+0000] {__init__.py:115} DEBUG - Preparing lineage inlets and outlets
[2025-02-19T10:24:47.450+0000] {__init__.py:154} DEBUG - inlets: [], outlets: []
[2025-02-19T10:24:47.451+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-02-19T10:24:47.451+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-02-19T10:24:47.452+0000] {logging_mixin.py:190} INFO - Current task name:ingest_postgres state:running start_date:2025-02-19 10:24:47.239559+00:00
[2025-02-19T10:24:47.452+0000] {logging_mixin.py:190} INFO - Dag name:etl_pipeline and current dag run status:running
[2025-02-19T10:24:47.452+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-19T10:24:47.474+0000] {etl_pipeline.py:75} INFO - Postgres data ingested and saved to /tmp/postgres_data.csv
[2025-02-19T10:24:47.475+0000] {python.py:240} INFO - Done. Returned value was: /tmp/postgres_data.csv
[2025-02-19T10:24:47.489+0000] {__init__.py:77} DEBUG - Lineage called with inlets: [], outlets: []
[2025-02-19T10:24:47.502+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-19T10:24:47.503+0000] {taskinstance.py:928} DEBUG - Clearing next_method and next_kwargs.
[2025-02-19T10:24:47.503+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_pipeline, task_id=ingest_postgres, run_id=manual__2025-02-19T10:24:41.603923+00:00, execution_date=20250219T102441, start_date=20250219T102447, end_date=20250219T102447
[2025-02-19T10:24:47.503+0000] {taskinstance.py:906} DEBUG - Task Duration set to 0.263657
[2025-02-19T10:24:47.515+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-02-19T10:24:47.516+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-02-19T10:24:47.516+0000] {logging_mixin.py:190} INFO - Dag name:etl_pipeline queued_at:2025-02-19 10:24:41.626406+00:00
[2025-02-19T10:24:47.517+0000] {logging_mixin.py:190} INFO - Task hostname:d01efb841c31 operator:PythonOperator
[2025-02-19T10:24:47.517+0000] {cli_action_loggers.py:98} DEBUG - Calling callbacks: []
[2025-02-19T10:24:47.565+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-19T10:24:47.582+0000] {dagrun.py:968} DEBUG - number of tis tasks for <DagRun etl_pipeline @ 2025-02-19 10:24:41.603923+00:00: manual__2025-02-19T10:24:41.603923+00:00, state:running, queued_at: 2025-02-19 10:24:41.626406+00:00. externally triggered: True>: 6 task(s)
[2025-02-19T10:24:47.582+0000] {dagrun.py:989} DEBUG - number of scheduleable tasks for <DagRun etl_pipeline @ 2025-02-19 10:24:41.603923+00:00: manual__2025-02-19T10:24:41.603923+00:00, state:running, queued_at: 2025-02-19 10:24:41.626406+00:00. externally triggered: True>: 3 task(s)
[2025-02-19T10:24:47.582+0000] {taskinstance.py:2624} DEBUG - <TaskInstance: etl_pipeline.validate_data manual__2025-02-19T10:24:41.603923+00:00 [None]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2025-02-19T10:24:47.583+0000] {taskinstance.py:2624} DEBUG - <TaskInstance: etl_pipeline.validate_data manual__2025-02-19T10:24:41.603923+00:00 [None]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2025-02-19T10:24:47.583+0000] {taskinstance.py:2624} DEBUG - <TaskInstance: etl_pipeline.validate_data manual__2025-02-19T10:24:41.603923+00:00 [None]> dependency 'Trigger Rule' PASSED: False, Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 2 non-success(es). upstream_states=_UpstreamTIStates(success=1, skipped=0, failed=0, upstream_failed=0, removed=0, done=1, success_setup=0, skipped_setup=0), upstream_task_ids={'ingest_api', 'ingest_postgres', 'ingest_csv'}
[2025-02-19T10:24:47.583+0000] {taskinstance.py:2602} DEBUG - Dependencies not met for <TaskInstance: etl_pipeline.validate_data manual__2025-02-19T10:24:41.603923+00:00 [None]>, dependency 'Trigger Rule' FAILED: Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 2 non-success(es). upstream_states=_UpstreamTIStates(success=1, skipped=0, failed=0, upstream_failed=0, removed=0, done=1, success_setup=0, skipped_setup=0), upstream_task_ids={'ingest_api', 'ingest_postgres', 'ingest_csv'}
[2025-02-19T10:24:47.584+0000] {taskinstance.py:2624} DEBUG - <TaskInstance: etl_pipeline.load_data manual__2025-02-19T10:24:41.603923+00:00 [None]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2025-02-19T10:24:47.584+0000] {taskinstance.py:2624} DEBUG - <TaskInstance: etl_pipeline.load_data manual__2025-02-19T10:24:41.603923+00:00 [None]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2025-02-19T10:24:47.584+0000] {taskinstance.py:2624} DEBUG - <TaskInstance: etl_pipeline.load_data manual__2025-02-19T10:24:41.603923+00:00 [None]> dependency 'Trigger Rule' PASSED: False, Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_states=_UpstreamTIStates(success=0, skipped=0, failed=0, upstream_failed=0, removed=0, done=0, success_setup=0, skipped_setup=0), upstream_task_ids={'validate_data'}
[2025-02-19T10:24:47.584+0000] {taskinstance.py:2602} DEBUG - Dependencies not met for <TaskInstance: etl_pipeline.load_data manual__2025-02-19T10:24:41.603923+00:00 [None]>, dependency 'Trigger Rule' FAILED: Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_states=_UpstreamTIStates(success=0, skipped=0, failed=0, upstream_failed=0, removed=0, done=0, success_setup=0, skipped_setup=0), upstream_task_ids={'validate_data'}
[2025-02-19T10:24:47.584+0000] {taskinstance.py:2624} DEBUG - <TaskInstance: etl_pipeline.send_alert manual__2025-02-19T10:24:41.603923+00:00 [None]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2025-02-19T10:24:47.584+0000] {taskinstance.py:2624} DEBUG - <TaskInstance: etl_pipeline.send_alert manual__2025-02-19T10:24:41.603923+00:00 [None]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2025-02-19T10:24:47.585+0000] {taskinstance.py:2624} DEBUG - <TaskInstance: etl_pipeline.send_alert manual__2025-02-19T10:24:41.603923+00:00 [None]> dependency 'Trigger Rule' PASSED: False, Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_states=_UpstreamTIStates(success=0, skipped=0, failed=0, upstream_failed=0, removed=0, done=0, success_setup=0, skipped_setup=0), upstream_task_ids={'validate_data'}
[2025-02-19T10:24:47.585+0000] {taskinstance.py:2602} DEBUG - Dependencies not met for <TaskInstance: etl_pipeline.send_alert manual__2025-02-19T10:24:41.603923+00:00 [None]>, dependency 'Trigger Rule' FAILED: Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_states=_UpstreamTIStates(success=0, skipped=0, failed=0, upstream_failed=0, removed=0, done=0, success_setup=0, skipped_setup=0), upstream_task_ids={'validate_data'}
[2025-02-19T10:24:47.589+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-19T10:24:47.591+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
