[2025-02-19T10:24:47.376+0000] {taskinstance.py:1402} DEBUG - previous_execution_date was called
[2025-02-19T10:24:47.399+0000] {__init__.py:54} DEBUG - Loading core task runner: StandardTaskRunner
[2025-02-19T10:24:47.411+0000] {taskinstance.py:1402} DEBUG - previous_execution_date was called
[2025-02-19T10:24:47.416+0000] {base_task_runner.py:73} DEBUG - Planning to run as the  user
[2025-02-19T10:24:47.420+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-19T10:24:47.430+0000] {taskinstance.py:2624} DEBUG - <TaskInstance: etl_pipeline.ingest_api manual__2025-02-19T10:24:41.603923+00:00 [queued]> dependency 'Task Instance State' PASSED: True, Task state queued was valid.
[2025-02-19T10:24:47.430+0000] {taskinstance.py:2624} DEBUG - <TaskInstance: etl_pipeline.ingest_api manual__2025-02-19T10:24:41.603923+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2025-02-19T10:24:47.438+0000] {taskinstance.py:2624} DEBUG - <TaskInstance: etl_pipeline.ingest_api manual__2025-02-19T10:24:41.603923+00:00 [queued]> dependency 'Trigger Rule' PASSED: True, The task instance did not have any upstream tasks.
[2025-02-19T10:24:47.439+0000] {taskinstance.py:2624} DEBUG - <TaskInstance: etl_pipeline.ingest_api manual__2025-02-19T10:24:41.603923+00:00 [queued]> dependency 'Task Instance Not Running' PASSED: True, Task is not in running state.
[2025-02-19T10:24:47.439+0000] {taskinstance.py:2624} DEBUG - <TaskInstance: etl_pipeline.ingest_api manual__2025-02-19T10:24:41.603923+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2025-02-19T10:24:47.439+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline.ingest_api manual__2025-02-19T10:24:41.603923+00:00 [queued]>
[2025-02-19T10:24:47.440+0000] {taskinstance.py:2624} DEBUG - <TaskInstance: etl_pipeline.ingest_api manual__2025-02-19T10:24:41.603923+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2025-02-19T10:24:47.440+0000] {taskinstance.py:2624} DEBUG - <TaskInstance: etl_pipeline.ingest_api manual__2025-02-19T10:24:41.603923+00:00 [queued]> dependency 'Task Concurrency' PASSED: True, Task concurrency is not set.
[2025-02-19T10:24:47.443+0000] {taskinstance.py:2624} DEBUG - <TaskInstance: etl_pipeline.ingest_api manual__2025-02-19T10:24:41.603923+00:00 [queued]> dependency 'Trigger Rule' PASSED: True, The task instance did not have any upstream tasks.
[2025-02-19T10:24:47.449+0000] {taskinstance.py:2624} DEBUG - <TaskInstance: etl_pipeline.ingest_api manual__2025-02-19T10:24:41.603923+00:00 [queued]> dependency 'Pool Slots Available' PASSED: True, There are enough open slots in default_pool to execute the task
[2025-02-19T10:24:47.453+0000] {taskinstance.py:2624} DEBUG - <TaskInstance: etl_pipeline.ingest_api manual__2025-02-19T10:24:41.603923+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2025-02-19T10:24:47.453+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline.ingest_api manual__2025-02-19T10:24:41.603923+00:00 [queued]>
[2025-02-19T10:24:47.453+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 3
[2025-02-19T10:24:47.469+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): ingest_api> on 2025-02-19 10:24:41.603923+00:00
[2025-02-19T10:24:47.477+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=83) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-19T10:24:47.478+0000] {standard_task_runner.py:72} INFO - Started process 89 to run task
[2025-02-19T10:24:47.479+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_pipeline', 'ingest_api', 'manual__2025-02-19T10:24:41.603923+00:00', '--job-id', '77', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpef9uvxel']
[2025-02-19T10:24:47.480+0000] {standard_task_runner.py:105} INFO - Job 77: Subtask ingest_api
[2025-02-19T10:24:47.480+0000] {cli_action_loggers.py:79} DEBUG - Calling callbacks: [<function default_action_log at 0x7fce9a04a340>]
[2025-02-19T10:24:47.525+0000] {taskinstance.py:1402} DEBUG - previous_execution_date was called
[2025-02-19T10:24:47.531+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_pipeline.ingest_api manual__2025-02-19T10:24:41.603923+00:00 [running]> on host d01efb841c31
[2025-02-19T10:24:47.531+0000] {settings.py:612} DEBUG - Disposing DB connection pool (PID 89)
[2025-02-19T10:24:47.532+0000] {settings.py:475} DEBUG - Setting up DB connection pool (PID 89)
[2025-02-19T10:24:47.532+0000] {settings.py:547} DEBUG - settings.prepare_engine_args(): Using NullPool
[2025-02-19T10:24:47.571+0000] {taskinstance.py:1402} DEBUG - previous_execution_date was called
[2025-02-19T10:24:47.577+0000] {taskinstance.py:2383} DEBUG - Clearing XCom data
[2025-02-19T10:24:47.585+0000] {retries.py:95} DEBUG - Running RenderedTaskInstanceFields.write with retries. Try 1 of 3
[2025-02-19T10:24:47.601+0000] {retries.py:95} DEBUG - Running RenderedTaskInstanceFields._do_delete_old_records with retries. Try 1 of 3
[2025-02-19T10:24:47.610+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='your_email@example.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_pipeline' AIRFLOW_CTX_TASK_ID='ingest_api' AIRFLOW_CTX_EXECUTION_DATE='2025-02-19T10:24:41.603923+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-19T10:24:41.603923+00:00'
[2025-02-19T10:24:47.610+0000] {__init__.py:115} DEBUG - Preparing lineage inlets and outlets
[2025-02-19T10:24:47.611+0000] {__init__.py:154} DEBUG - inlets: [], outlets: []
[2025-02-19T10:24:47.611+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-02-19T10:24:47.611+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-02-19T10:24:47.611+0000] {logging_mixin.py:190} INFO - Current task name:ingest_api state:running start_date:2025-02-19 10:24:47.440048+00:00
[2025-02-19T10:24:47.612+0000] {logging_mixin.py:190} INFO - Dag name:etl_pipeline and current dag run status:running
[2025-02-19T10:24:47.612+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-19T10:24:48.374+0000] {etl_pipeline.py:55} INFO - API data ingested and saved to /tmp/restcountries.json
[2025-02-19T10:24:48.377+0000] {python.py:240} INFO - Done. Returned value was: /tmp/restcountries.json
[2025-02-19T10:24:48.391+0000] {__init__.py:77} DEBUG - Lineage called with inlets: [], outlets: []
[2025-02-19T10:24:48.402+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-19T10:24:48.402+0000] {taskinstance.py:928} DEBUG - Clearing next_method and next_kwargs.
[2025-02-19T10:24:48.403+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_pipeline, task_id=ingest_api, run_id=manual__2025-02-19T10:24:41.603923+00:00, execution_date=20250219T102441, start_date=20250219T102447, end_date=20250219T102448
[2025-02-19T10:24:48.403+0000] {taskinstance.py:906} DEBUG - Task Duration set to 0.962943
[2025-02-19T10:24:48.412+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-02-19T10:24:48.412+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-02-19T10:24:48.413+0000] {logging_mixin.py:190} INFO - Dag name:etl_pipeline queued_at:2025-02-19 10:24:41.626406+00:00
[2025-02-19T10:24:48.413+0000] {logging_mixin.py:190} INFO - Task hostname:d01efb841c31 operator:PythonOperator
[2025-02-19T10:24:48.413+0000] {cli_action_loggers.py:98} DEBUG - Calling callbacks: []
[2025-02-19T10:24:48.456+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-19T10:24:48.474+0000] {dagrun.py:968} DEBUG - number of tis tasks for <DagRun etl_pipeline @ 2025-02-19 10:24:41.603923+00:00: manual__2025-02-19T10:24:41.603923+00:00, state:running, queued_at: 2025-02-19 10:24:41.626406+00:00. externally triggered: True>: 6 task(s)
[2025-02-19T10:24:48.474+0000] {dagrun.py:989} DEBUG - number of scheduleable tasks for <DagRun etl_pipeline @ 2025-02-19 10:24:41.603923+00:00: manual__2025-02-19T10:24:41.603923+00:00, state:running, queued_at: 2025-02-19 10:24:41.626406+00:00. externally triggered: True>: 3 task(s)
[2025-02-19T10:24:48.474+0000] {taskinstance.py:2624} DEBUG - <TaskInstance: etl_pipeline.validate_data manual__2025-02-19T10:24:41.603923+00:00 [None]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2025-02-19T10:24:48.475+0000] {taskinstance.py:2624} DEBUG - <TaskInstance: etl_pipeline.validate_data manual__2025-02-19T10:24:41.603923+00:00 [None]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2025-02-19T10:24:48.475+0000] {taskinstance.py:2612} DEBUG - Dependencies all met for dep_context=None ti=<TaskInstance: etl_pipeline.validate_data manual__2025-02-19T10:24:41.603923+00:00 [None]>
[2025-02-19T10:24:48.475+0000] {taskinstance.py:2624} DEBUG - <TaskInstance: etl_pipeline.load_data manual__2025-02-19T10:24:41.603923+00:00 [None]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2025-02-19T10:24:48.476+0000] {taskinstance.py:2624} DEBUG - <TaskInstance: etl_pipeline.load_data manual__2025-02-19T10:24:41.603923+00:00 [None]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2025-02-19T10:24:48.476+0000] {taskinstance.py:2624} DEBUG - <TaskInstance: etl_pipeline.load_data manual__2025-02-19T10:24:41.603923+00:00 [None]> dependency 'Trigger Rule' PASSED: False, Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_states=_UpstreamTIStates(success=0, skipped=0, failed=0, upstream_failed=0, removed=0, done=0, success_setup=0, skipped_setup=0), upstream_task_ids={'validate_data'}
[2025-02-19T10:24:48.476+0000] {taskinstance.py:2602} DEBUG - Dependencies not met for <TaskInstance: etl_pipeline.load_data manual__2025-02-19T10:24:41.603923+00:00 [None]>, dependency 'Trigger Rule' FAILED: Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_states=_UpstreamTIStates(success=0, skipped=0, failed=0, upstream_failed=0, removed=0, done=0, success_setup=0, skipped_setup=0), upstream_task_ids={'validate_data'}
[2025-02-19T10:24:48.476+0000] {taskinstance.py:2624} DEBUG - <TaskInstance: etl_pipeline.send_alert manual__2025-02-19T10:24:41.603923+00:00 [None]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2025-02-19T10:24:48.476+0000] {taskinstance.py:2624} DEBUG - <TaskInstance: etl_pipeline.send_alert manual__2025-02-19T10:24:41.603923+00:00 [None]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2025-02-19T10:24:48.477+0000] {taskinstance.py:2624} DEBUG - <TaskInstance: etl_pipeline.send_alert manual__2025-02-19T10:24:41.603923+00:00 [None]> dependency 'Trigger Rule' PASSED: False, Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_states=_UpstreamTIStates(success=0, skipped=0, failed=0, upstream_failed=0, removed=0, done=0, success_setup=0, skipped_setup=0), upstream_task_ids={'validate_data'}
[2025-02-19T10:24:48.477+0000] {taskinstance.py:2602} DEBUG - Dependencies not met for <TaskInstance: etl_pipeline.send_alert manual__2025-02-19T10:24:41.603923+00:00 [None]>, dependency 'Trigger Rule' FAILED: Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_states=_UpstreamTIStates(success=0, skipped=0, failed=0, upstream_failed=0, removed=0, done=0, success_setup=0, skipped_setup=0), upstream_task_ids={'validate_data'}
[2025-02-19T10:24:48.485+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-19T10:24:48.488+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
