[2025-02-18T17:25:00.001+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-18T17:25:00.018+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline.validate_data manual__2025-02-18T17:24:54.504035+00:00 [queued]>
[2025-02-18T17:25:00.026+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline.validate_data manual__2025-02-18T17:24:54.504035+00:00 [queued]>
[2025-02-18T17:25:00.026+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 3
[2025-02-18T17:25:00.039+0000] {taskinstance.py:2888} INFO - Executing <Task(BranchPythonOperator): validate_data> on 2025-02-18 17:24:54.504035+00:00
[2025-02-18T17:25:00.047+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=267) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-18T17:25:00.048+0000] {standard_task_runner.py:72} INFO - Started process 269 to run task
[2025-02-18T17:25:00.049+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_pipeline', 'validate_data', 'manual__2025-02-18T17:24:54.504035+00:00', '--job-id', '56', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmp6auv8mu7']
[2025-02-18T17:25:00.050+0000] {standard_task_runner.py:105} INFO - Job 56: Subtask validate_data
[2025-02-18T17:25:00.093+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_pipeline.validate_data manual__2025-02-18T17:24:54.504035+00:00 [running]> on host 06238f81c50a
[2025-02-18T17:25:00.165+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='your_email@example.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_pipeline' AIRFLOW_CTX_TASK_ID='validate_data' AIRFLOW_CTX_EXECUTION_DATE='2025-02-18T17:24:54.504035+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-18T17:24:54.504035+00:00'
[2025-02-18T17:25:00.166+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-02-18T17:25:00.166+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-02-18T17:25:00.167+0000] {logging_mixin.py:190} INFO - Current task name:validate_data state:running start_date:2025-02-18 17:25:00.018764+00:00
[2025-02-18T17:25:00.167+0000] {logging_mixin.py:190} INFO - Dag name:etl_pipeline and current dag run status:running
[2025-02-18T17:25:00.167+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-18T17:25:00.167+0000] {baseoperator.py:405} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2025-02-18T17:25:00.168+0000] {etl_pipeline.py:83} INFO - Validation passed.
[2025-02-18T17:25:00.168+0000] {python.py:240} INFO - Done. Returned value was: load_data
[2025-02-18T17:25:00.168+0000] {branch.py:38} INFO - Branch into load_data
[2025-02-18T17:25:00.168+0000] {skipmixin.py:230} INFO - Following branch ('load_data',)
[2025-02-18T17:25:00.183+0000] {skipmixin.py:278} INFO - Skipping tasks [('send_alert', -1)]
[2025-02-18T17:25:00.213+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-18T17:25:00.214+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_pipeline, task_id=validate_data, run_id=manual__2025-02-18T17:24:54.504035+00:00, execution_date=20250218T172454, start_date=20250218T172500, end_date=20250218T172500
[2025-02-18T17:25:00.221+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-02-18T17:25:00.222+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-02-18T17:25:00.222+0000] {logging_mixin.py:190} INFO - Dag name:etl_pipeline queued_at:2025-02-18 17:24:54.517366+00:00
[2025-02-18T17:25:00.222+0000] {logging_mixin.py:190} INFO - Task hostname:06238f81c50a operator:BranchPythonOperator
[2025-02-18T17:25:00.264+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-18T17:25:00.289+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-18T17:25:00.291+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
